Feature/documentation errors
MakaevaElena/graphiql-app pull request #66
Opened 2023-12-27 07:44 UTC by MakaevaElena

1. Task: [GraphiQL](https://github.com/rolling-scopes-school/tasks/blob/master/react/modules/graphiql.md)
2. Screenshot:
![image](https://github.com/MakaevaElena/graphiql-app/assets/87429007/46ff3da9-1821-449d-ae66-60098ecf2c83)

3. Deploy: [graphiql-app]()
4. Done 27.12.2023 / Deadline 08.01.2024

- [x] вывод ошибок  через notistack 
- [x] валидация url

- [ ] не получилось отловить ошибку CORS, выводится в консоль.

2023-12-27 09:09 UTC, AlexSerdyuk83 commented on src/Components/Endpoint/Endpoint.tsx
> +  const myHandleSubmit = (baseUrl: string) => {
какое-то странное название)

2023-12-27 09:09 UTC, AlexSerdyuk83 commented on src/Components/Endpoint/Endpoint.tsx
> +      if ('status' in error) {
Не очень хорошая история проверять наличие свойства объекта через in, потому что если у свойства будет значение undefined он тоже вернет true, а ниже ты проверяешь только на null еще и как строку + он проверяет свойства наследованные по цепосчке прототипов что тоже может вылезти боком. Лучше использовать hasOwn или на худой конец обратиться явно по ключу, но это тоже так себе история

2023-12-27 09:09 UTC, AlexSerdyuk83 commented on src/Components/Endpoint/Endpoint.tsx
> +        onChange={(event) => handleChangeUrl(event)}
Насколько мне известно, то в обработчик в любом случае попадет event? нет?
почему не так?:
```
        onChange={ handleChangeUrl}
```

2023-12-28 11:37 UTC, MakaevaElena commented on src/Components/Endpoint/Endpoint.tsx
> +  const myHandleSubmit = (baseUrl: string) => {
у formik свой встроенный handleSubmit,
чтобы отличать переименовывала )
сейчас уже не нужно, убрала my..

2023-12-28 14:13 UTC, surface74 requested changes
В доработку :)

2023-12-28 14:13 UTC, surface74 commented on src/Components/Endpoint/Endpoint.tsx
>    const schema = useFetchSchemaQuery(baseUrl);
Здесь возникает ошибка POST http://localhost:5173/Main 404 (Not Found), т.к. хук автоматически выполняет запрос с пустым baseUrl. В результате выполняем запрос к текущему адресу. Т.к. здесь запрос должен выполняться по нажатию кнопки, предлагаю использовать useLazyFetchSchemaQuery, как реализовано в компоненте ResponseSection после PR CORS-proxy.

2023-12-28 14:13 UTC, surface74 commented on src/Components/Endpoint/Endpoint.tsx
>    const { isLoading, isError, error } = useFetchSchemaQuery(baseUrl);
То же самое. Второй ошибки нет, вероятно, из-за кеширования запросов.

2023-12-28 14:13 UTC, surface74 commented on src/Components/Endpoint/Endpoint.tsx
Кнопка submit не отображается, если disabled===true (строки 116-118).

2023-12-28 14:13 UTC, surface74 commented on src/api/rtk-api.tsx
>      }),
Для чего будет использоваться этот action?

2023-12-28 14:17 UTC, MakaevaElena commented on src/Components/Endpoint/Endpoint.tsx
> +      if ('status' in error) {
ок
заменила проверку
Object.hasOwn(error.error, 'status'

2023-12-28 14:24 UTC, MakaevaElena commented on src/Components/Endpoint/Endpoint.tsx
> +        onChange={(event) => handleChangeUrl(event)}
TS периодически ругался в процессе, добавила так, сейчас убрала, норм.

2023-12-28 18:02 UTC, MakaevaElena commented on src/api/rtk-api.tsx
>      }),
если с CORS решиться, то будут доступны мутации, хочу попробовать такой запрос сделать.

2023-12-28 18:04 UTC, MakaevaElena commented on src/Components/Endpoint/Endpoint.tsx
>    const schema = useFetchSchemaQuery(baseUrl);
добавила useLazyFetchSchemaQuery
404 ушла

2023-12-28 21:33 UTC, surface74 approved these changes
Обязательно нужно сделать очистку ошибки в store после ее отображения

2023-12-28 21:33 UTC, surface74 commented on src/Components/Endpoint/Endpoint.tsx
> +  const errorApiMessage = useAppSelector((store) => store.ApiData.errorMessage);
Лучше использовать деструктуризацию:
`const { baseUrl, errorMessage: errorApiMessage } = useAppSelector((store) => store.ApiData);`

2023-12-28 21:33 UTC, surface74 commented on src/Components/Endpoint/Endpoint.tsx
> +      });
Следующей командой нужно очищать ошибку в store, иначе при следующих нажатиях кнопки не выводятся ошибки:
`dispatch(setApiErrorMessage(''));`

Вообще проброс ошибки через store в таком виде в асинхронной системе кажется сомнительной идеей. Нужно подумать :)

2023-12-28 21:33 UTC, surface74 commented on src/Components/Endpoint/Endpoint.tsx
> +    }
Предлагаю написать так:
```
const isButtonDisabled = !!!data || isError || !!error || !baseUrl;
setDocsButtonDisabled(isButtonDisabled );
```

2023-12-28 21:33 UTC, surface74 commented on src/Components/Endpoint/Endpoint.tsx
> +    isLoading ? setIsLoadingSchema(true) : setIsLoadingSchema(false);
Предлагаю написать так:
`setIsLoadingSchema(isLoading);`

2023-12-29 02:55 UTC, MakaevaElena commented on src/Components/Endpoint/Endpoint.tsx
> +  const errorApiMessage = useAppSelector((store) => store.ApiData.errorMessage);
+

2023-12-29 02:57 UTC, MakaevaElena commented on src/Components/Endpoint/Endpoint.tsx
> +    }
+

2023-12-29 02:58 UTC, MakaevaElena commented on src/Components/Endpoint/Endpoint.tsx
> +    isLoading ? setIsLoadingSchema(true) : setIsLoadingSchema(false);
+

2023-12-29 03:05 UTC, MakaevaElena commented on src/Components/Endpoint/Endpoint.tsx
> +      });
+

2023-12-29 09:40 UTC, MaleryValery approved these changes

2023-12-29 09:41 UTC, MaleryValery approved these changes

2023-12-29 10:14 UTC, merged