Tests/docs - new PR
MakaevaElena/graphiql-app pull request #91
Opened 2024-01-03 11:45 UTC by MakaevaElena

1. Task: [GraphiQL](https://github.com/rolling-scopes-school/tasks/blob/master/react/modules/graphiql.md)
2. Screenshot:
![image](https://github.com/MakaevaElena/graphiql-app/assets/87429007/465cce4a-cb68-406c-840e-22119f760178)

3. Deploy: [graphiql-app]()
4. Done 03.01.2024 / Deadline 08.01.2024

Написала немного тестов.
Для компонентов:

Documentation
ErrorBoundary
NotFoundPage
и слайсов (UISlice, querySlice, apiSlice, userSlice)

В процессе написания для Endpoint.
Endpoint буду отдельным PR делать, т.к. там оказалось сложно, застряла (.

2024-01-03 12:10 UTC, surface74 requested changes
Заменить get* -метод на find*

2024-01-03 12:10 UTC, surface74 commented on src/Components/Documentation/DocsSection.test.tsx
> +    const subSectionDescription = screen.getByText(
Будет периодически глючить. Для ожидаемого контента, который появится после асинхронных событий, нужно использовать find* методы, get* - для сразу загружаемого DOM-дерева.
https://testing-library.com/docs/dom-testing-library/api-async

2024-01-03 12:10 UTC, surface74 commented on src/Components/Endpoint/Schema.test.jsx
> +    });
Вместо waitFor лучше использовать find* методы:
https://kentcdodds.com/blog/common-mistakes-with-react-testing-library#using-waitfor-to-wait-for-elements-that-can-be-queried-with-find

2024-01-03 14:20 UTC, MakaevaElena commented on src/Components/Documentation/DocsSection.test.tsx
> +    const subSectionDescription = screen.getByText(
+

2024-01-03 14:23 UTC, MakaevaElena commented on src/Components/Endpoint/Schema.test.jsx
> +    });
+

2024-01-03 14:25 UTC, MakaevaElena commented
поиски после fireEvent заменила на find

2024-01-03 18:19 UTC, surface74 approved these changes
OK

2024-01-04 17:14 UTC, MaleryValery approved these changes

2024-01-04 17:25 UTC, merged